### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by ghost** [Skillmon/ltx_ducksay#2]
This may be stupid question, but when I was using the packages, my Texworks consistently gives me error (using pdfLaTeX or pdfTeX). I tried overleaf too, but it does not work well either. It compiles but there is something wrong with the dialog box. I'd appreciate it if you could help. Thanks!

Edit: This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6840 64-bit)
I got error messages:
("C:\Users\xx\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\latin1.def
")) (ducksay.sty
("C:\Users\xx\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3packages\xparse
\xparse.sty"
("C:\Users\xx\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3kernel\expl3.st
y"
("C:\Users\xx\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3kernel\expl3-co
de.tex")
("C:\Users\xx\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3kernel\l3pdfmod
e.def")))
("C:\Users\xx\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3packages\l3keys
2e\l3keys2e.sty") (ducksay.code.v2.tex

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.

I do have \begin{document} in code. When I comment out the \usepackage{ducksay}, everything runs.

**Comment by Skillmon** [comment]
Can you provide a complete minimal example that produces your error? Please also provide a complete log file while using `\listfiles` in your document.

**Comment by Skillmon** [comment]
Overleaf seems to not have `ducksay` installed at all. There is nothing I can do about that (but you could contact and ask them to add it).

**Comment by Skillmon** [comment]
I've just asked someone who has access to a working MiKTeX installation and he can compile `\documentclass{article}\usepackage{ducksay}\begin{document}test\end{document}` without any errors. So please update your MiKTeX installation to the latest version and then try again. Please understand that I don't support older versions as keeping packages compatible with every version of every LaTeX distribution seems like an unmanageable huge task to me.

Please tell me whether everything works after updating and if not what is still wrong.

**Comment by Skillmon** [comment]
I'm closing the issue as of now. If you come back to this providing an example where `ducksay` fails with a recent TeX Live or MiKTeX installation, I'll reopen the issue and try to solve it.
